name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21

    - name: Build Spring Boot JAR
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{gniharika26 }}
        password: ${{Banny@2604 }}

    - name: Build Docker Image
      run: docker build -t gniharika26/job-portal-app:latest .

    - name: Push Docker Image
      run: docker push gniharika26/job-portal-app:latest
